# 1 ветка, 3 коммита: 2024-10-25 2 коммита, 2024-10-26 один
# repo_path: "../../git-repo" 
# 2 ветки: 2024-10-29 с ветками, 2024-11-03 ещё один
repo_path: "../../git-two-branches"
# 1 ветка, 3 коммита: 2024-10-29 все
# repo_path: "../../git-help-repo"
pumlfile_path: "./pumlfile.puml"
start_date: "2022-10-25"